INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-01-01', 'Año Nuevo', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-03-25', 'Viernes Santo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-03-26', 'Sabado Santo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-05-01', 'Día Nacional del Trabajo', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-05-21', 'Día de las Glorias Navales', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-06-07', 'Asalto y Toma del Morro de Arica', 'Sólo en Región de Arica y Parinacota');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-06-19', 'Elecciones Primarias Municipales', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-06-27', 'San Pedro y San Pablo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-07-16', 'Día de la Virgen del Carme', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-08-15', 'Asunción de la Virgen', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-08-20', 'Nacimiento del Prócer de la Independencia', 'Sólo en Comunas de Chillán y Chillán Viejo');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-09-18', 'Independencia Nacional', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-09-19', 'Día de las Glorias del Ejército', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-10-10', 'Encuentro de Dos Mundos', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-10-23', 'Elecciones Municipales', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-10-31', 'Día de las Iglesias Evangélicas y Protestantes', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-11-01', 'Día de Todos los Santos', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-12-08', 'Inmaculada Concepción', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-12-25', 'Navidad', 'Religioso e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2016-12-31', 'Feriado Bancario', 'Sólo para Trabajadores de Instituciones Bancarias');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-01-01', 'Año Nuevo', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-03-25', 'Viernes Santo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-03-26', 'Sabado Santo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-05-01', 'Día Nacional del Trabajo', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-05-21', 'Día de las Glorias Navales', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-06-07', 'Asalto y Toma del Morro de Arica', 'Sólo en Región de Arica y Parinacota');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-06-19', 'Elecciones Primarias Municipales', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-06-27', 'San Pedro y San Pablo', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-07-16', 'Día de la Virgen del Carme', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-08-15', 'Asunción de la Virgen', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-08-20', 'Nacimiento del Prócer de la Independencia', 'Sólo en Comunas de Chillán y Chillán Viejo');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-09-18', 'Independencia Nacional', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-09-19', 'Día de las Glorias del Ejército', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-10-10', 'Encuentro de Dos Mundos', 'Civil');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-10-23', 'Elecciones Municipales', 'Civil e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-10-31', 'Día de las Iglesias Evangélicas y Protestantes', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-11-01', 'Día de Todos los Santos', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-12-08', 'Inmaculada Concepción', 'Religioso');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-12-25', 'Navidad', 'Religioso e Irrenunciable');
INSERT INTO dias_feriados (date_at, title, extra) VALUES ('2017-12-31', 'Feriado Bancario', 'Sólo para Trabajadores de Instituciones Bancarias');